// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ErrorRes;
@class ErrorRes_Builder;

@interface BaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ErrorRes : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasCategory_:1;
  BOOL hasTitle_:1;
  BOOL hasTip_:1;
  int32_t status;
  int32_t category;
  NSString* title;
  NSString* tip;
}
- (BOOL) hasStatus;
- (BOOL) hasCategory;
- (BOOL) hasTitle;
- (BOOL) hasTip;
@property (readonly) int32_t status;
@property (readonly) int32_t category;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* tip;

+ (ErrorRes*) defaultInstance;
- (ErrorRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ErrorRes_Builder*) builder;
+ (ErrorRes_Builder*) builder;
+ (ErrorRes_Builder*) builderWithPrototype:(ErrorRes*) prototype;

+ (ErrorRes*) parseFromData:(NSData*) data;
+ (ErrorRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorRes*) parseFromInputStream:(NSInputStream*) input;
+ (ErrorRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ErrorRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ErrorRes_Builder : PBGeneratedMessage_Builder {
@private
  ErrorRes* result;
}

- (ErrorRes*) defaultInstance;

- (ErrorRes_Builder*) clear;
- (ErrorRes_Builder*) clone;

- (ErrorRes*) build;
- (ErrorRes*) buildPartial;

- (ErrorRes_Builder*) mergeFrom:(ErrorRes*) other;
- (ErrorRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ErrorRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (ErrorRes_Builder*) setStatus:(int32_t) value;
- (ErrorRes_Builder*) clearStatus;

- (BOOL) hasCategory;
- (int32_t) category;
- (ErrorRes_Builder*) setCategory:(int32_t) value;
- (ErrorRes_Builder*) clearCategory;

- (BOOL) hasTitle;
- (NSString*) title;
- (ErrorRes_Builder*) setTitle:(NSString*) value;
- (ErrorRes_Builder*) clearTitle;

- (BOOL) hasTip;
- (NSString*) tip;
- (ErrorRes_Builder*) setTip:(NSString*) value;
- (ErrorRes_Builder*) clearTip;
@end

