// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class FruitMessageProto;
@class FruitMessageProto_Builder;

@interface FriutRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface FruitMessageProto : PBGeneratedMessage {
@private
  BOOL hasMsgId_:1;
  BOOL hasUserId_:1;
  BOOL hasHeader_:1;
  BOOL hasVersion_:1;
  BOOL hasContent_:1;
  int32_t msgId;
  int32_t userId;
  NSString* header;
  NSString* version;
  NSData* content;
}
- (BOOL) hasHeader;
- (BOOL) hasMsgId;
- (BOOL) hasVersion;
- (BOOL) hasContent;
- (BOOL) hasUserId;
@property (readonly, retain) NSString* header;
@property (readonly) int32_t msgId;
@property (readonly, retain) NSString* version;
@property (readonly, retain) NSData* content;
@property (readonly) int32_t userId;

+ (FruitMessageProto*) defaultInstance;
- (FruitMessageProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FruitMessageProto_Builder*) builder;
+ (FruitMessageProto_Builder*) builder;
+ (FruitMessageProto_Builder*) builderWithPrototype:(FruitMessageProto*) prototype;

+ (FruitMessageProto*) parseFromData:(NSData*) data;
+ (FruitMessageProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FruitMessageProto*) parseFromInputStream:(NSInputStream*) input;
+ (FruitMessageProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FruitMessageProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FruitMessageProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FruitMessageProto_Builder : PBGeneratedMessage_Builder {
@private
  FruitMessageProto* result;
}

- (FruitMessageProto*) defaultInstance;

- (FruitMessageProto_Builder*) clear;
- (FruitMessageProto_Builder*) clone;

- (FruitMessageProto*) build;
- (FruitMessageProto*) buildPartial;

- (FruitMessageProto_Builder*) mergeFrom:(FruitMessageProto*) other;
- (FruitMessageProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FruitMessageProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHeader;
- (NSString*) header;
- (FruitMessageProto_Builder*) setHeader:(NSString*) value;
- (FruitMessageProto_Builder*) clearHeader;

- (BOOL) hasMsgId;
- (int32_t) msgId;
- (FruitMessageProto_Builder*) setMsgId:(int32_t) value;
- (FruitMessageProto_Builder*) clearMsgId;

- (BOOL) hasVersion;
- (NSString*) version;
- (FruitMessageProto_Builder*) setVersion:(NSString*) value;
- (FruitMessageProto_Builder*) clearVersion;

- (BOOL) hasContent;
- (NSData*) content;
- (FruitMessageProto_Builder*) setContent:(NSData*) value;
- (FruitMessageProto_Builder*) clearContent;

- (BOOL) hasUserId;
- (int32_t) userId;
- (FruitMessageProto_Builder*) setUserId:(int32_t) value;
- (FruitMessageProto_Builder*) clearUserId;
@end

