// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetLotteryListReq;
@class GetLotteryListReq_Builder;
@class GetLotteryListRes;
@class GetLotteryListRes_Builder;
@class GetLotteryReq;
@class GetLotteryReq_Builder;
@class GetLotteryRes;
@class GetLotteryRes_Builder;
@class LotteryInfo;
@class LotteryInfo_Builder;
@class LotteryPrizeInfo;
@class LotteryPrizeInfo_Builder;

@interface LotteryRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetLotteryListReq : PBGeneratedMessage {
@private
}

+ (GetLotteryListReq*) defaultInstance;
- (GetLotteryListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetLotteryListReq_Builder*) builder;
+ (GetLotteryListReq_Builder*) builder;
+ (GetLotteryListReq_Builder*) builderWithPrototype:(GetLotteryListReq*) prototype;

+ (GetLotteryListReq*) parseFromData:(NSData*) data;
+ (GetLotteryListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryListReq*) parseFromInputStream:(NSInputStream*) input;
+ (GetLotteryListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetLotteryListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetLotteryListReq_Builder : PBGeneratedMessage_Builder {
@private
  GetLotteryListReq* result;
}

- (GetLotteryListReq*) defaultInstance;

- (GetLotteryListReq_Builder*) clear;
- (GetLotteryListReq_Builder*) clone;

- (GetLotteryListReq*) build;
- (GetLotteryListReq*) buildPartial;

- (GetLotteryListReq_Builder*) mergeFrom:(GetLotteryListReq*) other;
- (GetLotteryListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetLotteryListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LotteryPrizeInfo : PBGeneratedMessage {
@private
  BOOL hasPrizeId_:1;
  BOOL hasPrizePic_:1;
  BOOL hasPrizeName_:1;
  int32_t prizeId;
  NSString* prizePic;
  NSString* prizeName;
}
- (BOOL) hasPrizeId;
- (BOOL) hasPrizePic;
- (BOOL) hasPrizeName;
@property (readonly) int32_t prizeId;
@property (readonly, retain) NSString* prizePic;
@property (readonly, retain) NSString* prizeName;

+ (LotteryPrizeInfo*) defaultInstance;
- (LotteryPrizeInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LotteryPrizeInfo_Builder*) builder;
+ (LotteryPrizeInfo_Builder*) builder;
+ (LotteryPrizeInfo_Builder*) builderWithPrototype:(LotteryPrizeInfo*) prototype;

+ (LotteryPrizeInfo*) parseFromData:(NSData*) data;
+ (LotteryPrizeInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LotteryPrizeInfo*) parseFromInputStream:(NSInputStream*) input;
+ (LotteryPrizeInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LotteryPrizeInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LotteryPrizeInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LotteryPrizeInfo_Builder : PBGeneratedMessage_Builder {
@private
  LotteryPrizeInfo* result;
}

- (LotteryPrizeInfo*) defaultInstance;

- (LotteryPrizeInfo_Builder*) clear;
- (LotteryPrizeInfo_Builder*) clone;

- (LotteryPrizeInfo*) build;
- (LotteryPrizeInfo*) buildPartial;

- (LotteryPrizeInfo_Builder*) mergeFrom:(LotteryPrizeInfo*) other;
- (LotteryPrizeInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LotteryPrizeInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPrizeId;
- (int32_t) prizeId;
- (LotteryPrizeInfo_Builder*) setPrizeId:(int32_t) value;
- (LotteryPrizeInfo_Builder*) clearPrizeId;

- (BOOL) hasPrizePic;
- (NSString*) prizePic;
- (LotteryPrizeInfo_Builder*) setPrizePic:(NSString*) value;
- (LotteryPrizeInfo_Builder*) clearPrizePic;

- (BOOL) hasPrizeName;
- (NSString*) prizeName;
- (LotteryPrizeInfo_Builder*) setPrizeName:(NSString*) value;
- (LotteryPrizeInfo_Builder*) clearPrizeName;
@end

@interface LotteryInfo : PBGeneratedMessage {
@private
  BOOL hasLotteryId_:1;
  BOOL hasLotteryCost_:1;
  BOOL hasLotteryName_:1;
  BOOL hasLotteryDesc_:1;
  int32_t lotteryId;
  int32_t lotteryCost;
  NSString* lotteryName;
  NSString* lotteryDesc;
  NSMutableArray* mutablePrizesList;
}
- (BOOL) hasLotteryId;
- (BOOL) hasLotteryName;
- (BOOL) hasLotteryDesc;
- (BOOL) hasLotteryCost;
@property (readonly) int32_t lotteryId;
@property (readonly, retain) NSString* lotteryName;
@property (readonly, retain) NSString* lotteryDesc;
@property (readonly) int32_t lotteryCost;
- (NSArray*) prizesList;
- (LotteryPrizeInfo*) prizesAtIndex:(int32_t) index;

+ (LotteryInfo*) defaultInstance;
- (LotteryInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LotteryInfo_Builder*) builder;
+ (LotteryInfo_Builder*) builder;
+ (LotteryInfo_Builder*) builderWithPrototype:(LotteryInfo*) prototype;

+ (LotteryInfo*) parseFromData:(NSData*) data;
+ (LotteryInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LotteryInfo*) parseFromInputStream:(NSInputStream*) input;
+ (LotteryInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LotteryInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LotteryInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LotteryInfo_Builder : PBGeneratedMessage_Builder {
@private
  LotteryInfo* result;
}

- (LotteryInfo*) defaultInstance;

- (LotteryInfo_Builder*) clear;
- (LotteryInfo_Builder*) clone;

- (LotteryInfo*) build;
- (LotteryInfo*) buildPartial;

- (LotteryInfo_Builder*) mergeFrom:(LotteryInfo*) other;
- (LotteryInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LotteryInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLotteryId;
- (int32_t) lotteryId;
- (LotteryInfo_Builder*) setLotteryId:(int32_t) value;
- (LotteryInfo_Builder*) clearLotteryId;

- (BOOL) hasLotteryName;
- (NSString*) lotteryName;
- (LotteryInfo_Builder*) setLotteryName:(NSString*) value;
- (LotteryInfo_Builder*) clearLotteryName;

- (BOOL) hasLotteryDesc;
- (NSString*) lotteryDesc;
- (LotteryInfo_Builder*) setLotteryDesc:(NSString*) value;
- (LotteryInfo_Builder*) clearLotteryDesc;

- (BOOL) hasLotteryCost;
- (int32_t) lotteryCost;
- (LotteryInfo_Builder*) setLotteryCost:(int32_t) value;
- (LotteryInfo_Builder*) clearLotteryCost;

- (NSArray*) prizesList;
- (LotteryPrizeInfo*) prizesAtIndex:(int32_t) index;
- (LotteryInfo_Builder*) replacePrizesAtIndex:(int32_t) index with:(LotteryPrizeInfo*) value;
- (LotteryInfo_Builder*) addPrizes:(LotteryPrizeInfo*) value;
- (LotteryInfo_Builder*) addAllPrizes:(NSArray*) values;
- (LotteryInfo_Builder*) clearPrizesList;
@end

@interface GetLotteryListRes : PBGeneratedMessage {
@private
  BOOL hasLotteryCount_:1;
  int32_t lotteryCount;
  NSMutableArray* mutableLotteryInfosList;
}
- (BOOL) hasLotteryCount;
@property (readonly) int32_t lotteryCount;
- (NSArray*) lotteryInfosList;
- (LotteryInfo*) lotteryInfosAtIndex:(int32_t) index;

+ (GetLotteryListRes*) defaultInstance;
- (GetLotteryListRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetLotteryListRes_Builder*) builder;
+ (GetLotteryListRes_Builder*) builder;
+ (GetLotteryListRes_Builder*) builderWithPrototype:(GetLotteryListRes*) prototype;

+ (GetLotteryListRes*) parseFromData:(NSData*) data;
+ (GetLotteryListRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryListRes*) parseFromInputStream:(NSInputStream*) input;
+ (GetLotteryListRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetLotteryListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetLotteryListRes_Builder : PBGeneratedMessage_Builder {
@private
  GetLotteryListRes* result;
}

- (GetLotteryListRes*) defaultInstance;

- (GetLotteryListRes_Builder*) clear;
- (GetLotteryListRes_Builder*) clone;

- (GetLotteryListRes*) build;
- (GetLotteryListRes*) buildPartial;

- (GetLotteryListRes_Builder*) mergeFrom:(GetLotteryListRes*) other;
- (GetLotteryListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetLotteryListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLotteryCount;
- (int32_t) lotteryCount;
- (GetLotteryListRes_Builder*) setLotteryCount:(int32_t) value;
- (GetLotteryListRes_Builder*) clearLotteryCount;

- (NSArray*) lotteryInfosList;
- (LotteryInfo*) lotteryInfosAtIndex:(int32_t) index;
- (GetLotteryListRes_Builder*) replaceLotteryInfosAtIndex:(int32_t) index with:(LotteryInfo*) value;
- (GetLotteryListRes_Builder*) addLotteryInfos:(LotteryInfo*) value;
- (GetLotteryListRes_Builder*) addAllLotteryInfos:(NSArray*) values;
- (GetLotteryListRes_Builder*) clearLotteryInfosList;
@end

@interface GetLotteryReq : PBGeneratedMessage {
@private
  BOOL hasLotteryId_:1;
  int32_t lotteryId;
}
- (BOOL) hasLotteryId;
@property (readonly) int32_t lotteryId;

+ (GetLotteryReq*) defaultInstance;
- (GetLotteryReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetLotteryReq_Builder*) builder;
+ (GetLotteryReq_Builder*) builder;
+ (GetLotteryReq_Builder*) builderWithPrototype:(GetLotteryReq*) prototype;

+ (GetLotteryReq*) parseFromData:(NSData*) data;
+ (GetLotteryReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryReq*) parseFromInputStream:(NSInputStream*) input;
+ (GetLotteryReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetLotteryReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetLotteryReq_Builder : PBGeneratedMessage_Builder {
@private
  GetLotteryReq* result;
}

- (GetLotteryReq*) defaultInstance;

- (GetLotteryReq_Builder*) clear;
- (GetLotteryReq_Builder*) clone;

- (GetLotteryReq*) build;
- (GetLotteryReq*) buildPartial;

- (GetLotteryReq_Builder*) mergeFrom:(GetLotteryReq*) other;
- (GetLotteryReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetLotteryReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLotteryId;
- (int32_t) lotteryId;
- (GetLotteryReq_Builder*) setLotteryId:(int32_t) value;
- (GetLotteryReq_Builder*) clearLotteryId;
@end

@interface GetLotteryRes : PBGeneratedMessage {
@private
  BOOL hasPrizeId_:1;
  BOOL hasPrizePic_:1;
  BOOL hasPrizeName_:1;
  int32_t prizeId;
  NSString* prizePic;
  NSString* prizeName;
}
- (BOOL) hasPrizeId;
- (BOOL) hasPrizePic;
- (BOOL) hasPrizeName;
@property (readonly) int32_t prizeId;
@property (readonly, retain) NSString* prizePic;
@property (readonly, retain) NSString* prizeName;

+ (GetLotteryRes*) defaultInstance;
- (GetLotteryRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetLotteryRes_Builder*) builder;
+ (GetLotteryRes_Builder*) builder;
+ (GetLotteryRes_Builder*) builderWithPrototype:(GetLotteryRes*) prototype;

+ (GetLotteryRes*) parseFromData:(NSData*) data;
+ (GetLotteryRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryRes*) parseFromInputStream:(NSInputStream*) input;
+ (GetLotteryRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetLotteryRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetLotteryRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetLotteryRes_Builder : PBGeneratedMessage_Builder {
@private
  GetLotteryRes* result;
}

- (GetLotteryRes*) defaultInstance;

- (GetLotteryRes_Builder*) clear;
- (GetLotteryRes_Builder*) clone;

- (GetLotteryRes*) build;
- (GetLotteryRes*) buildPartial;

- (GetLotteryRes_Builder*) mergeFrom:(GetLotteryRes*) other;
- (GetLotteryRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetLotteryRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPrizeId;
- (int32_t) prizeId;
- (GetLotteryRes_Builder*) setPrizeId:(int32_t) value;
- (GetLotteryRes_Builder*) clearPrizeId;

- (BOOL) hasPrizePic;
- (NSString*) prizePic;
- (GetLotteryRes_Builder*) setPrizePic:(NSString*) value;
- (GetLotteryRes_Builder*) clearPrizePic;

- (BOOL) hasPrizeName;
- (NSString*) prizeName;
- (GetLotteryRes_Builder*) setPrizeName:(NSString*) value;
- (GetLotteryRes_Builder*) clearPrizeName;
@end

