// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AnteRatio;
@class AnteRatio_Builder;
@class AnteUpResultRes;
@class AnteUpResultRes_Builder;
@class AnteUpUserInfo;
@class AnteUpUserInfo_Builder;
@class MatchAnteUpReq;
@class MatchAnteUpReq_Builder;
@class MatchListRes;
@class MatchListRes_Builder;
@class UserAnteUpRes;
@class UserAnteUpRes_Builder;

@interface MatchRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AnteRatio : PBGeneratedMessage {
@private
  BOOL hasPoint_:1;
  BOOL hasRatio_:1;
  int32_t point;
  int32_t ratio;
}
- (BOOL) hasPoint;
- (BOOL) hasRatio;
@property (readonly) int32_t point;
@property (readonly) int32_t ratio;

+ (AnteRatio*) defaultInstance;
- (AnteRatio*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnteRatio_Builder*) builder;
+ (AnteRatio_Builder*) builder;
+ (AnteRatio_Builder*) builderWithPrototype:(AnteRatio*) prototype;

+ (AnteRatio*) parseFromData:(NSData*) data;
+ (AnteRatio*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteRatio*) parseFromInputStream:(NSInputStream*) input;
+ (AnteRatio*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteRatio*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AnteRatio*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnteRatio_Builder : PBGeneratedMessage_Builder {
@private
  AnteRatio* result;
}

- (AnteRatio*) defaultInstance;

- (AnteRatio_Builder*) clear;
- (AnteRatio_Builder*) clone;

- (AnteRatio*) build;
- (AnteRatio*) buildPartial;

- (AnteRatio_Builder*) mergeFrom:(AnteRatio*) other;
- (AnteRatio_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnteRatio_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPoint;
- (int32_t) point;
- (AnteRatio_Builder*) setPoint:(int32_t) value;
- (AnteRatio_Builder*) clearPoint;

- (BOOL) hasRatio;
- (int32_t) ratio;
- (AnteRatio_Builder*) setRatio:(int32_t) value;
- (AnteRatio_Builder*) clearRatio;
@end

@interface MatchListRes : PBGeneratedMessage {
@private
  BOOL hasTimes_:1;
  int32_t times;
  NSMutableArray* mutableAnteRatioList;
}
- (BOOL) hasTimes;
@property (readonly) int32_t times;
- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;

+ (MatchListRes*) defaultInstance;
- (MatchListRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MatchListRes_Builder*) builder;
+ (MatchListRes_Builder*) builder;
+ (MatchListRes_Builder*) builderWithPrototype:(MatchListRes*) prototype;

+ (MatchListRes*) parseFromData:(NSData*) data;
+ (MatchListRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MatchListRes*) parseFromInputStream:(NSInputStream*) input;
+ (MatchListRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MatchListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MatchListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MatchListRes_Builder : PBGeneratedMessage_Builder {
@private
  MatchListRes* result;
}

- (MatchListRes*) defaultInstance;

- (MatchListRes_Builder*) clear;
- (MatchListRes_Builder*) clone;

- (MatchListRes*) build;
- (MatchListRes*) buildPartial;

- (MatchListRes_Builder*) mergeFrom:(MatchListRes*) other;
- (MatchListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MatchListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTimes;
- (int32_t) times;
- (MatchListRes_Builder*) setTimes:(int32_t) value;
- (MatchListRes_Builder*) clearTimes;

- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;
- (MatchListRes_Builder*) replaceAnteRatioAtIndex:(int32_t) index with:(AnteRatio*) value;
- (MatchListRes_Builder*) addAnteRatio:(AnteRatio*) value;
- (MatchListRes_Builder*) addAllAnteRatio:(NSArray*) values;
- (MatchListRes_Builder*) clearAnteRatioList;
@end

@interface MatchAnteUpReq : PBGeneratedMessage {
@private
  BOOL hasRoomId_:1;
  BOOL hasDeskId_:1;
  int32_t roomId;
  int32_t deskId;
  NSMutableArray* mutableAnteRatioList;
}
- (BOOL) hasRoomId;
- (BOOL) hasDeskId;
@property (readonly) int32_t roomId;
@property (readonly) int32_t deskId;
- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;

+ (MatchAnteUpReq*) defaultInstance;
- (MatchAnteUpReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MatchAnteUpReq_Builder*) builder;
+ (MatchAnteUpReq_Builder*) builder;
+ (MatchAnteUpReq_Builder*) builderWithPrototype:(MatchAnteUpReq*) prototype;

+ (MatchAnteUpReq*) parseFromData:(NSData*) data;
+ (MatchAnteUpReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MatchAnteUpReq*) parseFromInputStream:(NSInputStream*) input;
+ (MatchAnteUpReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MatchAnteUpReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MatchAnteUpReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MatchAnteUpReq_Builder : PBGeneratedMessage_Builder {
@private
  MatchAnteUpReq* result;
}

- (MatchAnteUpReq*) defaultInstance;

- (MatchAnteUpReq_Builder*) clear;
- (MatchAnteUpReq_Builder*) clone;

- (MatchAnteUpReq*) build;
- (MatchAnteUpReq*) buildPartial;

- (MatchAnteUpReq_Builder*) mergeFrom:(MatchAnteUpReq*) other;
- (MatchAnteUpReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MatchAnteUpReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (MatchAnteUpReq_Builder*) setRoomId:(int32_t) value;
- (MatchAnteUpReq_Builder*) clearRoomId;

- (BOOL) hasDeskId;
- (int32_t) deskId;
- (MatchAnteUpReq_Builder*) setDeskId:(int32_t) value;
- (MatchAnteUpReq_Builder*) clearDeskId;

- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;
- (MatchAnteUpReq_Builder*) replaceAnteRatioAtIndex:(int32_t) index with:(AnteRatio*) value;
- (MatchAnteUpReq_Builder*) addAnteRatio:(AnteRatio*) value;
- (MatchAnteUpReq_Builder*) addAllAnteRatio:(NSArray*) values;
- (MatchAnteUpReq_Builder*) clearAnteRatioList;
@end

@interface UserAnteUpRes : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  int32_t userId;
  NSMutableArray* mutableAnteRatioList;
}
- (BOOL) hasUserId;
@property (readonly) int32_t userId;
- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;

+ (UserAnteUpRes*) defaultInstance;
- (UserAnteUpRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserAnteUpRes_Builder*) builder;
+ (UserAnteUpRes_Builder*) builder;
+ (UserAnteUpRes_Builder*) builderWithPrototype:(UserAnteUpRes*) prototype;

+ (UserAnteUpRes*) parseFromData:(NSData*) data;
+ (UserAnteUpRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAnteUpRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserAnteUpRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAnteUpRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserAnteUpRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserAnteUpRes_Builder : PBGeneratedMessage_Builder {
@private
  UserAnteUpRes* result;
}

- (UserAnteUpRes*) defaultInstance;

- (UserAnteUpRes_Builder*) clear;
- (UserAnteUpRes_Builder*) clone;

- (UserAnteUpRes*) build;
- (UserAnteUpRes*) buildPartial;

- (UserAnteUpRes_Builder*) mergeFrom:(UserAnteUpRes*) other;
- (UserAnteUpRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserAnteUpRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserAnteUpRes_Builder*) setUserId:(int32_t) value;
- (UserAnteUpRes_Builder*) clearUserId;

- (NSArray*) anteRatioList;
- (AnteRatio*) anteRatioAtIndex:(int32_t) index;
- (UserAnteUpRes_Builder*) replaceAnteRatioAtIndex:(int32_t) index with:(AnteRatio*) value;
- (UserAnteUpRes_Builder*) addAnteRatio:(AnteRatio*) value;
- (UserAnteUpRes_Builder*) addAllAnteRatio:(NSArray*) values;
- (UserAnteUpRes_Builder*) clearAnteRatioList;
@end

@interface AnteUpUserInfo : PBGeneratedMessage {
@private
  BOOL hasExperience_:1;
  BOOL hasNextExperience_:1;
  BOOL hasUserId_:1;
  BOOL hasCoin_:1;
  BOOL hasLottery_:1;
  BOOL hasContinueWinCount_:1;
  BOOL hasIsUp_:1;
  int64_t experience;
  int64_t nextExperience;
  int32_t userId;
  int32_t coin;
  int32_t lottery;
  int32_t continueWinCount;
  int32_t isUp;
}
- (BOOL) hasUserId;
- (BOOL) hasCoin;
- (BOOL) hasLottery;
- (BOOL) hasContinueWinCount;
- (BOOL) hasExperience;
- (BOOL) hasNextExperience;
- (BOOL) hasIsUp;
@property (readonly) int32_t userId;
@property (readonly) int32_t coin;
@property (readonly) int32_t lottery;
@property (readonly) int32_t continueWinCount;
@property (readonly) int64_t experience;
@property (readonly) int64_t nextExperience;
@property (readonly) int32_t isUp;

+ (AnteUpUserInfo*) defaultInstance;
- (AnteUpUserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnteUpUserInfo_Builder*) builder;
+ (AnteUpUserInfo_Builder*) builder;
+ (AnteUpUserInfo_Builder*) builderWithPrototype:(AnteUpUserInfo*) prototype;

+ (AnteUpUserInfo*) parseFromData:(NSData*) data;
+ (AnteUpUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteUpUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (AnteUpUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteUpUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AnteUpUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnteUpUserInfo_Builder : PBGeneratedMessage_Builder {
@private
  AnteUpUserInfo* result;
}

- (AnteUpUserInfo*) defaultInstance;

- (AnteUpUserInfo_Builder*) clear;
- (AnteUpUserInfo_Builder*) clone;

- (AnteUpUserInfo*) build;
- (AnteUpUserInfo*) buildPartial;

- (AnteUpUserInfo_Builder*) mergeFrom:(AnteUpUserInfo*) other;
- (AnteUpUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnteUpUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (AnteUpUserInfo_Builder*) setUserId:(int32_t) value;
- (AnteUpUserInfo_Builder*) clearUserId;

- (BOOL) hasCoin;
- (int32_t) coin;
- (AnteUpUserInfo_Builder*) setCoin:(int32_t) value;
- (AnteUpUserInfo_Builder*) clearCoin;

- (BOOL) hasLottery;
- (int32_t) lottery;
- (AnteUpUserInfo_Builder*) setLottery:(int32_t) value;
- (AnteUpUserInfo_Builder*) clearLottery;

- (BOOL) hasContinueWinCount;
- (int32_t) continueWinCount;
- (AnteUpUserInfo_Builder*) setContinueWinCount:(int32_t) value;
- (AnteUpUserInfo_Builder*) clearContinueWinCount;

- (BOOL) hasExperience;
- (int64_t) experience;
- (AnteUpUserInfo_Builder*) setExperience:(int64_t) value;
- (AnteUpUserInfo_Builder*) clearExperience;

- (BOOL) hasNextExperience;
- (int64_t) nextExperience;
- (AnteUpUserInfo_Builder*) setNextExperience:(int64_t) value;
- (AnteUpUserInfo_Builder*) clearNextExperience;

- (BOOL) hasIsUp;
- (int32_t) isUp;
- (AnteUpUserInfo_Builder*) setIsUp:(int32_t) value;
- (AnteUpUserInfo_Builder*) clearIsUp;
@end

@interface AnteUpResultRes : PBGeneratedMessage {
@private
  BOOL hasPoint_:1;
  int32_t point;
  NSMutableArray* mutableAnteUpUserInfosList;
}
- (BOOL) hasPoint;
@property (readonly) int32_t point;
- (NSArray*) anteUpUserInfosList;
- (AnteUpUserInfo*) anteUpUserInfosAtIndex:(int32_t) index;

+ (AnteUpResultRes*) defaultInstance;
- (AnteUpResultRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnteUpResultRes_Builder*) builder;
+ (AnteUpResultRes_Builder*) builder;
+ (AnteUpResultRes_Builder*) builderWithPrototype:(AnteUpResultRes*) prototype;

+ (AnteUpResultRes*) parseFromData:(NSData*) data;
+ (AnteUpResultRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteUpResultRes*) parseFromInputStream:(NSInputStream*) input;
+ (AnteUpResultRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteUpResultRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AnteUpResultRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnteUpResultRes_Builder : PBGeneratedMessage_Builder {
@private
  AnteUpResultRes* result;
}

- (AnteUpResultRes*) defaultInstance;

- (AnteUpResultRes_Builder*) clear;
- (AnteUpResultRes_Builder*) clone;

- (AnteUpResultRes*) build;
- (AnteUpResultRes*) buildPartial;

- (AnteUpResultRes_Builder*) mergeFrom:(AnteUpResultRes*) other;
- (AnteUpResultRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnteUpResultRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPoint;
- (int32_t) point;
- (AnteUpResultRes_Builder*) setPoint:(int32_t) value;
- (AnteUpResultRes_Builder*) clearPoint;

- (NSArray*) anteUpUserInfosList;
- (AnteUpUserInfo*) anteUpUserInfosAtIndex:(int32_t) index;
- (AnteUpResultRes_Builder*) replaceAnteUpUserInfosAtIndex:(int32_t) index with:(AnteUpUserInfo*) value;
- (AnteUpResultRes_Builder*) addAnteUpUserInfos:(AnteUpUserInfo*) value;
- (AnteUpResultRes_Builder*) addAllAnteUpUserInfos:(NSArray*) values;
- (AnteUpResultRes_Builder*) clearAnteUpUserInfosList;
@end

