// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetRankListReq;
@class GetRankListReq_Builder;
@class GetRankListRes;
@class GetRankListRes_Builder;
@class RankInfo;
@class RankInfo_Builder;

@interface RankRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetRankListReq : PBGeneratedMessage {
@private
  BOOL hasRank_:1;
  BOOL hasCount_:1;
  int32_t rank;
  int32_t count;
}
- (BOOL) hasRank;
- (BOOL) hasCount;
@property (readonly) int32_t rank;
@property (readonly) int32_t count;

+ (GetRankListReq*) defaultInstance;
- (GetRankListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetRankListReq_Builder*) builder;
+ (GetRankListReq_Builder*) builder;
+ (GetRankListReq_Builder*) builderWithPrototype:(GetRankListReq*) prototype;

+ (GetRankListReq*) parseFromData:(NSData*) data;
+ (GetRankListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRankListReq*) parseFromInputStream:(NSInputStream*) input;
+ (GetRankListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRankListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetRankListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetRankListReq_Builder : PBGeneratedMessage_Builder {
@private
  GetRankListReq* result;
}

- (GetRankListReq*) defaultInstance;

- (GetRankListReq_Builder*) clear;
- (GetRankListReq_Builder*) clone;

- (GetRankListReq*) build;
- (GetRankListReq*) buildPartial;

- (GetRankListReq_Builder*) mergeFrom:(GetRankListReq*) other;
- (GetRankListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetRankListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRank;
- (int32_t) rank;
- (GetRankListReq_Builder*) setRank:(int32_t) value;
- (GetRankListReq_Builder*) clearRank;

- (BOOL) hasCount;
- (int32_t) count;
- (GetRankListReq_Builder*) setCount:(int32_t) value;
- (GetRankListReq_Builder*) clearCount;
@end

@interface RankInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserRank_:1;
  BOOL hasCoin_:1;
  BOOL hasRank_:1;
  BOOL hasUserName_:1;
  int32_t userId;
  int32_t userRank;
  int32_t coin;
  int32_t rank;
  NSString* userName;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasUserRank;
- (BOOL) hasCoin;
- (BOOL) hasRank;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly) int32_t userRank;
@property (readonly) int32_t coin;
@property (readonly) int32_t rank;

+ (RankInfo*) defaultInstance;
- (RankInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RankInfo_Builder*) builder;
+ (RankInfo_Builder*) builder;
+ (RankInfo_Builder*) builderWithPrototype:(RankInfo*) prototype;

+ (RankInfo*) parseFromData:(NSData*) data;
+ (RankInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RankInfo*) parseFromInputStream:(NSInputStream*) input;
+ (RankInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RankInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RankInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RankInfo_Builder : PBGeneratedMessage_Builder {
@private
  RankInfo* result;
}

- (RankInfo*) defaultInstance;

- (RankInfo_Builder*) clear;
- (RankInfo_Builder*) clone;

- (RankInfo*) build;
- (RankInfo*) buildPartial;

- (RankInfo_Builder*) mergeFrom:(RankInfo*) other;
- (RankInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RankInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (RankInfo_Builder*) setUserId:(int32_t) value;
- (RankInfo_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (RankInfo_Builder*) setUserName:(NSString*) value;
- (RankInfo_Builder*) clearUserName;

- (BOOL) hasUserRank;
- (int32_t) userRank;
- (RankInfo_Builder*) setUserRank:(int32_t) value;
- (RankInfo_Builder*) clearUserRank;

- (BOOL) hasCoin;
- (int32_t) coin;
- (RankInfo_Builder*) setCoin:(int32_t) value;
- (RankInfo_Builder*) clearCoin;

- (BOOL) hasRank;
- (int32_t) rank;
- (RankInfo_Builder*) setRank:(int32_t) value;
- (RankInfo_Builder*) clearRank;
@end

@interface GetRankListRes : PBGeneratedMessage {
@private
  BOOL hasSelfRank_:1;
  int32_t selfRank;
  NSMutableArray* mutableRankInfosList;
}
- (BOOL) hasSelfRank;
@property (readonly) int32_t selfRank;
- (NSArray*) rankInfosList;
- (RankInfo*) rankInfosAtIndex:(int32_t) index;

+ (GetRankListRes*) defaultInstance;
- (GetRankListRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetRankListRes_Builder*) builder;
+ (GetRankListRes_Builder*) builder;
+ (GetRankListRes_Builder*) builderWithPrototype:(GetRankListRes*) prototype;

+ (GetRankListRes*) parseFromData:(NSData*) data;
+ (GetRankListRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRankListRes*) parseFromInputStream:(NSInputStream*) input;
+ (GetRankListRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRankListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetRankListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetRankListRes_Builder : PBGeneratedMessage_Builder {
@private
  GetRankListRes* result;
}

- (GetRankListRes*) defaultInstance;

- (GetRankListRes_Builder*) clear;
- (GetRankListRes_Builder*) clone;

- (GetRankListRes*) build;
- (GetRankListRes*) buildPartial;

- (GetRankListRes_Builder*) mergeFrom:(GetRankListRes*) other;
- (GetRankListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetRankListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSelfRank;
- (int32_t) selfRank;
- (GetRankListRes_Builder*) setSelfRank:(int32_t) value;
- (GetRankListRes_Builder*) clearSelfRank;

- (NSArray*) rankInfosList;
- (RankInfo*) rankInfosAtIndex:(int32_t) index;
- (GetRankListRes_Builder*) replaceRankInfosAtIndex:(int32_t) index with:(RankInfo*) value;
- (GetRankListRes_Builder*) addRankInfos:(RankInfo*) value;
- (GetRankListRes_Builder*) addAllRankInfos:(NSArray*) values;
- (GetRankListRes_Builder*) clearRankInfosList;
@end

