// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AnteInfo;
@class AnteInfo_Builder;
@class EnterRoomPushRes;
@class EnterRoomPushRes_Builder;
@class EnterRoomReq;
@class EnterRoomReq_Builder;
@class EnterRoomRes;
@class EnterRoomRes_Builder;
@class GetRoomListReq;
@class GetRoomListReq_Builder;
@class GetRoomListRes;
@class GetRoomListRes_Builder;
@class RoomAnteRes;
@class RoomAnteRes_Builder;
@class RoomExitRes;
@class RoomExitRes_Builder;
@class RoomInfo;
@class RoomInfo_Builder;
@class RoomTipRes;
@class RoomTipRes_Builder;
@class RoomUserInfo;
@class RoomUserInfo_Builder;

@interface RoomRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetRoomListReq : PBGeneratedMessage {
@private
  BOOL hasRoomId_:1;
  BOOL hasCount_:1;
  int64_t roomId;
  int32_t count;
}
- (BOOL) hasRoomId;
- (BOOL) hasCount;
@property (readonly) int64_t roomId;
@property (readonly) int32_t count;

+ (GetRoomListReq*) defaultInstance;
- (GetRoomListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetRoomListReq_Builder*) builder;
+ (GetRoomListReq_Builder*) builder;
+ (GetRoomListReq_Builder*) builderWithPrototype:(GetRoomListReq*) prototype;

+ (GetRoomListReq*) parseFromData:(NSData*) data;
+ (GetRoomListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRoomListReq*) parseFromInputStream:(NSInputStream*) input;
+ (GetRoomListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRoomListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetRoomListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetRoomListReq_Builder : PBGeneratedMessage_Builder {
@private
  GetRoomListReq* result;
}

- (GetRoomListReq*) defaultInstance;

- (GetRoomListReq_Builder*) clear;
- (GetRoomListReq_Builder*) clone;

- (GetRoomListReq*) build;
- (GetRoomListReq*) buildPartial;

- (GetRoomListReq_Builder*) mergeFrom:(GetRoomListReq*) other;
- (GetRoomListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetRoomListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int64_t) roomId;
- (GetRoomListReq_Builder*) setRoomId:(int64_t) value;
- (GetRoomListReq_Builder*) clearRoomId;

- (BOOL) hasCount;
- (int32_t) count;
- (GetRoomListReq_Builder*) setCount:(int32_t) value;
- (GetRoomListReq_Builder*) clearCount;
@end

@interface RoomInfo : PBGeneratedMessage {
@private
  BOOL hasRoomId_:1;
  BOOL hasNeedRank_:1;
  BOOL hasLowCoin_:1;
  BOOL hasRoomName_:1;
  BOOL hasRoomDesc_:1;
  BOOL hasRoomPic_:1;
  int32_t roomId;
  int32_t needRank;
  int32_t lowCoin;
  NSString* roomName;
  NSString* roomDesc;
  NSString* roomPic;
}
- (BOOL) hasRoomId;
- (BOOL) hasRoomName;
- (BOOL) hasRoomDesc;
- (BOOL) hasNeedRank;
- (BOOL) hasLowCoin;
- (BOOL) hasRoomPic;
@property (readonly) int32_t roomId;
@property (readonly, retain) NSString* roomName;
@property (readonly, retain) NSString* roomDesc;
@property (readonly) int32_t needRank;
@property (readonly) int32_t lowCoin;
@property (readonly, retain) NSString* roomPic;

+ (RoomInfo*) defaultInstance;
- (RoomInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomInfo_Builder*) builder;
+ (RoomInfo_Builder*) builder;
+ (RoomInfo_Builder*) builderWithPrototype:(RoomInfo*) prototype;

+ (RoomInfo*) parseFromData:(NSData*) data;
+ (RoomInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input;
+ (RoomInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomInfo_Builder : PBGeneratedMessage_Builder {
@private
  RoomInfo* result;
}

- (RoomInfo*) defaultInstance;

- (RoomInfo_Builder*) clear;
- (RoomInfo_Builder*) clone;

- (RoomInfo*) build;
- (RoomInfo*) buildPartial;

- (RoomInfo_Builder*) mergeFrom:(RoomInfo*) other;
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (RoomInfo_Builder*) setRoomId:(int32_t) value;
- (RoomInfo_Builder*) clearRoomId;

- (BOOL) hasRoomName;
- (NSString*) roomName;
- (RoomInfo_Builder*) setRoomName:(NSString*) value;
- (RoomInfo_Builder*) clearRoomName;

- (BOOL) hasRoomDesc;
- (NSString*) roomDesc;
- (RoomInfo_Builder*) setRoomDesc:(NSString*) value;
- (RoomInfo_Builder*) clearRoomDesc;

- (BOOL) hasNeedRank;
- (int32_t) needRank;
- (RoomInfo_Builder*) setNeedRank:(int32_t) value;
- (RoomInfo_Builder*) clearNeedRank;

- (BOOL) hasLowCoin;
- (int32_t) lowCoin;
- (RoomInfo_Builder*) setLowCoin:(int32_t) value;
- (RoomInfo_Builder*) clearLowCoin;

- (BOOL) hasRoomPic;
- (NSString*) roomPic;
- (RoomInfo_Builder*) setRoomPic:(NSString*) value;
- (RoomInfo_Builder*) clearRoomPic;
@end

@interface GetRoomListRes : PBGeneratedMessage {
@private
  NSMutableArray* mutableRoomInfosList;
}
- (NSArray*) roomInfosList;
- (RoomInfo*) roomInfosAtIndex:(int32_t) index;

+ (GetRoomListRes*) defaultInstance;
- (GetRoomListRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetRoomListRes_Builder*) builder;
+ (GetRoomListRes_Builder*) builder;
+ (GetRoomListRes_Builder*) builderWithPrototype:(GetRoomListRes*) prototype;

+ (GetRoomListRes*) parseFromData:(NSData*) data;
+ (GetRoomListRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRoomListRes*) parseFromInputStream:(NSInputStream*) input;
+ (GetRoomListRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRoomListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetRoomListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetRoomListRes_Builder : PBGeneratedMessage_Builder {
@private
  GetRoomListRes* result;
}

- (GetRoomListRes*) defaultInstance;

- (GetRoomListRes_Builder*) clear;
- (GetRoomListRes_Builder*) clone;

- (GetRoomListRes*) build;
- (GetRoomListRes*) buildPartial;

- (GetRoomListRes_Builder*) mergeFrom:(GetRoomListRes*) other;
- (GetRoomListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetRoomListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) roomInfosList;
- (RoomInfo*) roomInfosAtIndex:(int32_t) index;
- (GetRoomListRes_Builder*) replaceRoomInfosAtIndex:(int32_t) index with:(RoomInfo*) value;
- (GetRoomListRes_Builder*) addRoomInfos:(RoomInfo*) value;
- (GetRoomListRes_Builder*) addAllRoomInfos:(NSArray*) values;
- (GetRoomListRes_Builder*) clearRoomInfosList;
@end

@interface EnterRoomReq : PBGeneratedMessage {
@private
  BOOL hasRoomId_:1;
  int32_t roomId;
}
- (BOOL) hasRoomId;
@property (readonly) int32_t roomId;

+ (EnterRoomReq*) defaultInstance;
- (EnterRoomReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnterRoomReq_Builder*) builder;
+ (EnterRoomReq_Builder*) builder;
+ (EnterRoomReq_Builder*) builderWithPrototype:(EnterRoomReq*) prototype;

+ (EnterRoomReq*) parseFromData:(NSData*) data;
+ (EnterRoomReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomReq*) parseFromInputStream:(NSInputStream*) input;
+ (EnterRoomReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnterRoomReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnterRoomReq_Builder : PBGeneratedMessage_Builder {
@private
  EnterRoomReq* result;
}

- (EnterRoomReq*) defaultInstance;

- (EnterRoomReq_Builder*) clear;
- (EnterRoomReq_Builder*) clone;

- (EnterRoomReq*) build;
- (EnterRoomReq*) buildPartial;

- (EnterRoomReq_Builder*) mergeFrom:(EnterRoomReq*) other;
- (EnterRoomReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnterRoomReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (EnterRoomReq_Builder*) setRoomId:(int32_t) value;
- (EnterRoomReq_Builder*) clearRoomId;
@end

@interface EnterRoomRes : PBGeneratedMessage {
@private
  BOOL hasRoomId_:1;
  BOOL hasDeskId_:1;
  int32_t roomId;
  int32_t deskId;
}
- (BOOL) hasRoomId;
- (BOOL) hasDeskId;
@property (readonly) int32_t roomId;
@property (readonly) int32_t deskId;

+ (EnterRoomRes*) defaultInstance;
- (EnterRoomRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnterRoomRes_Builder*) builder;
+ (EnterRoomRes_Builder*) builder;
+ (EnterRoomRes_Builder*) builderWithPrototype:(EnterRoomRes*) prototype;

+ (EnterRoomRes*) parseFromData:(NSData*) data;
+ (EnterRoomRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomRes*) parseFromInputStream:(NSInputStream*) input;
+ (EnterRoomRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnterRoomRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnterRoomRes_Builder : PBGeneratedMessage_Builder {
@private
  EnterRoomRes* result;
}

- (EnterRoomRes*) defaultInstance;

- (EnterRoomRes_Builder*) clear;
- (EnterRoomRes_Builder*) clone;

- (EnterRoomRes*) build;
- (EnterRoomRes*) buildPartial;

- (EnterRoomRes_Builder*) mergeFrom:(EnterRoomRes*) other;
- (EnterRoomRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnterRoomRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoomId;
- (int32_t) roomId;
- (EnterRoomRes_Builder*) setRoomId:(int32_t) value;
- (EnterRoomRes_Builder*) clearRoomId;

- (BOOL) hasDeskId;
- (int32_t) deskId;
- (EnterRoomRes_Builder*) setDeskId:(int32_t) value;
- (EnterRoomRes_Builder*) clearDeskId;
@end

@interface AnteInfo : PBGeneratedMessage {
@private
  BOOL hasPoint_:1;
  BOOL hasCount_:1;
  int32_t point;
  int32_t count;
}
- (BOOL) hasPoint;
- (BOOL) hasCount;
@property (readonly) int32_t point;
@property (readonly) int32_t count;

+ (AnteInfo*) defaultInstance;
- (AnteInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnteInfo_Builder*) builder;
+ (AnteInfo_Builder*) builder;
+ (AnteInfo_Builder*) builderWithPrototype:(AnteInfo*) prototype;

+ (AnteInfo*) parseFromData:(NSData*) data;
+ (AnteInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteInfo*) parseFromInputStream:(NSInputStream*) input;
+ (AnteInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AnteInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AnteInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnteInfo_Builder : PBGeneratedMessage_Builder {
@private
  AnteInfo* result;
}

- (AnteInfo*) defaultInstance;

- (AnteInfo_Builder*) clear;
- (AnteInfo_Builder*) clone;

- (AnteInfo*) build;
- (AnteInfo*) buildPartial;

- (AnteInfo_Builder*) mergeFrom:(AnteInfo*) other;
- (AnteInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnteInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPoint;
- (int32_t) point;
- (AnteInfo_Builder*) setPoint:(int32_t) value;
- (AnteInfo_Builder*) clearPoint;

- (BOOL) hasCount;
- (int32_t) count;
- (AnteInfo_Builder*) setCount:(int32_t) value;
- (AnteInfo_Builder*) clearCount;
@end

@interface RoomUserInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasUserRank_:1;
  int32_t userId;
  NSString* userName;
  NSString* userRank;
  NSMutableArray* mutableAnteInfosList;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasUserRank;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* userRank;
- (NSArray*) anteInfosList;
- (AnteInfo*) anteInfosAtIndex:(int32_t) index;

+ (RoomUserInfo*) defaultInstance;
- (RoomUserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomUserInfo_Builder*) builder;
+ (RoomUserInfo_Builder*) builder;
+ (RoomUserInfo_Builder*) builderWithPrototype:(RoomUserInfo*) prototype;

+ (RoomUserInfo*) parseFromData:(NSData*) data;
+ (RoomUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (RoomUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomUserInfo_Builder : PBGeneratedMessage_Builder {
@private
  RoomUserInfo* result;
}

- (RoomUserInfo*) defaultInstance;

- (RoomUserInfo_Builder*) clear;
- (RoomUserInfo_Builder*) clone;

- (RoomUserInfo*) build;
- (RoomUserInfo*) buildPartial;

- (RoomUserInfo_Builder*) mergeFrom:(RoomUserInfo*) other;
- (RoomUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (RoomUserInfo_Builder*) setUserId:(int32_t) value;
- (RoomUserInfo_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (RoomUserInfo_Builder*) setUserName:(NSString*) value;
- (RoomUserInfo_Builder*) clearUserName;

- (BOOL) hasUserRank;
- (NSString*) userRank;
- (RoomUserInfo_Builder*) setUserRank:(NSString*) value;
- (RoomUserInfo_Builder*) clearUserRank;

- (NSArray*) anteInfosList;
- (AnteInfo*) anteInfosAtIndex:(int32_t) index;
- (RoomUserInfo_Builder*) replaceAnteInfosAtIndex:(int32_t) index with:(AnteInfo*) value;
- (RoomUserInfo_Builder*) addAnteInfos:(AnteInfo*) value;
- (RoomUserInfo_Builder*) addAllAnteInfos:(NSArray*) values;
- (RoomUserInfo_Builder*) clearAnteInfosList;
@end

@interface RoomAnteRes : PBGeneratedMessage {
@private
  NSMutableArray* mutableRoomUserInfosList;
}
- (NSArray*) roomUserInfosList;
- (RoomUserInfo*) roomUserInfosAtIndex:(int32_t) index;

+ (RoomAnteRes*) defaultInstance;
- (RoomAnteRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomAnteRes_Builder*) builder;
+ (RoomAnteRes_Builder*) builder;
+ (RoomAnteRes_Builder*) builderWithPrototype:(RoomAnteRes*) prototype;

+ (RoomAnteRes*) parseFromData:(NSData*) data;
+ (RoomAnteRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomAnteRes*) parseFromInputStream:(NSInputStream*) input;
+ (RoomAnteRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomAnteRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomAnteRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomAnteRes_Builder : PBGeneratedMessage_Builder {
@private
  RoomAnteRes* result;
}

- (RoomAnteRes*) defaultInstance;

- (RoomAnteRes_Builder*) clear;
- (RoomAnteRes_Builder*) clone;

- (RoomAnteRes*) build;
- (RoomAnteRes*) buildPartial;

- (RoomAnteRes_Builder*) mergeFrom:(RoomAnteRes*) other;
- (RoomAnteRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomAnteRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) roomUserInfosList;
- (RoomUserInfo*) roomUserInfosAtIndex:(int32_t) index;
- (RoomAnteRes_Builder*) replaceRoomUserInfosAtIndex:(int32_t) index with:(RoomUserInfo*) value;
- (RoomAnteRes_Builder*) addRoomUserInfos:(RoomUserInfo*) value;
- (RoomAnteRes_Builder*) addAllRoomUserInfos:(NSArray*) values;
- (RoomAnteRes_Builder*) clearRoomUserInfosList;
@end

@interface RoomTipRes : PBGeneratedMessage {
@private
  BOOL hasTip_:1;
  NSString* tip;
}
- (BOOL) hasTip;
@property (readonly, retain) NSString* tip;

+ (RoomTipRes*) defaultInstance;
- (RoomTipRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomTipRes_Builder*) builder;
+ (RoomTipRes_Builder*) builder;
+ (RoomTipRes_Builder*) builderWithPrototype:(RoomTipRes*) prototype;

+ (RoomTipRes*) parseFromData:(NSData*) data;
+ (RoomTipRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomTipRes*) parseFromInputStream:(NSInputStream*) input;
+ (RoomTipRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomTipRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomTipRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomTipRes_Builder : PBGeneratedMessage_Builder {
@private
  RoomTipRes* result;
}

- (RoomTipRes*) defaultInstance;

- (RoomTipRes_Builder*) clear;
- (RoomTipRes_Builder*) clone;

- (RoomTipRes*) build;
- (RoomTipRes*) buildPartial;

- (RoomTipRes_Builder*) mergeFrom:(RoomTipRes*) other;
- (RoomTipRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomTipRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTip;
- (NSString*) tip;
- (RoomTipRes_Builder*) setTip:(NSString*) value;
- (RoomTipRes_Builder*) clearTip;
@end

@interface EnterRoomPushRes : PBGeneratedMessage {
@private
  BOOL hasExperience_:1;
  BOOL hasNextExperience_:1;
  BOOL hasCoin_:1;
  BOOL hasUserId_:1;
  BOOL hasRank_:1;
  BOOL hasLottery_:1;
  BOOL hasVip_:1;
  BOOL hasUserName_:1;
  BOOL hasPhotoUrl_:1;
  int64_t experience;
  int64_t nextExperience;
  int64_t coin;
  int32_t userId;
  int32_t rank;
  int32_t lottery;
  int32_t vip;
  NSString* userName;
  NSString* photoUrl;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasRank;
- (BOOL) hasExperience;
- (BOOL) hasNextExperience;
- (BOOL) hasCoin;
- (BOOL) hasLottery;
- (BOOL) hasPhotoUrl;
- (BOOL) hasVip;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly) int32_t rank;
@property (readonly) int64_t experience;
@property (readonly) int64_t nextExperience;
@property (readonly) int64_t coin;
@property (readonly) int32_t lottery;
@property (readonly, retain) NSString* photoUrl;
@property (readonly) int32_t vip;

+ (EnterRoomPushRes*) defaultInstance;
- (EnterRoomPushRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnterRoomPushRes_Builder*) builder;
+ (EnterRoomPushRes_Builder*) builder;
+ (EnterRoomPushRes_Builder*) builderWithPrototype:(EnterRoomPushRes*) prototype;

+ (EnterRoomPushRes*) parseFromData:(NSData*) data;
+ (EnterRoomPushRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomPushRes*) parseFromInputStream:(NSInputStream*) input;
+ (EnterRoomPushRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnterRoomPushRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnterRoomPushRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnterRoomPushRes_Builder : PBGeneratedMessage_Builder {
@private
  EnterRoomPushRes* result;
}

- (EnterRoomPushRes*) defaultInstance;

- (EnterRoomPushRes_Builder*) clear;
- (EnterRoomPushRes_Builder*) clone;

- (EnterRoomPushRes*) build;
- (EnterRoomPushRes*) buildPartial;

- (EnterRoomPushRes_Builder*) mergeFrom:(EnterRoomPushRes*) other;
- (EnterRoomPushRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnterRoomPushRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (EnterRoomPushRes_Builder*) setUserId:(int32_t) value;
- (EnterRoomPushRes_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (EnterRoomPushRes_Builder*) setUserName:(NSString*) value;
- (EnterRoomPushRes_Builder*) clearUserName;

- (BOOL) hasRank;
- (int32_t) rank;
- (EnterRoomPushRes_Builder*) setRank:(int32_t) value;
- (EnterRoomPushRes_Builder*) clearRank;

- (BOOL) hasExperience;
- (int64_t) experience;
- (EnterRoomPushRes_Builder*) setExperience:(int64_t) value;
- (EnterRoomPushRes_Builder*) clearExperience;

- (BOOL) hasNextExperience;
- (int64_t) nextExperience;
- (EnterRoomPushRes_Builder*) setNextExperience:(int64_t) value;
- (EnterRoomPushRes_Builder*) clearNextExperience;

- (BOOL) hasCoin;
- (int64_t) coin;
- (EnterRoomPushRes_Builder*) setCoin:(int64_t) value;
- (EnterRoomPushRes_Builder*) clearCoin;

- (BOOL) hasLottery;
- (int32_t) lottery;
- (EnterRoomPushRes_Builder*) setLottery:(int32_t) value;
- (EnterRoomPushRes_Builder*) clearLottery;

- (BOOL) hasPhotoUrl;
- (NSString*) photoUrl;
- (EnterRoomPushRes_Builder*) setPhotoUrl:(NSString*) value;
- (EnterRoomPushRes_Builder*) clearPhotoUrl;

- (BOOL) hasVip;
- (int32_t) vip;
- (EnterRoomPushRes_Builder*) setVip:(int32_t) value;
- (EnterRoomPushRes_Builder*) clearVip;
@end

@interface RoomExitRes : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  int32_t userId;
}
- (BOOL) hasUserId;
@property (readonly) int32_t userId;

+ (RoomExitRes*) defaultInstance;
- (RoomExitRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RoomExitRes_Builder*) builder;
+ (RoomExitRes_Builder*) builder;
+ (RoomExitRes_Builder*) builderWithPrototype:(RoomExitRes*) prototype;

+ (RoomExitRes*) parseFromData:(NSData*) data;
+ (RoomExitRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomExitRes*) parseFromInputStream:(NSInputStream*) input;
+ (RoomExitRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RoomExitRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RoomExitRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RoomExitRes_Builder : PBGeneratedMessage_Builder {
@private
  RoomExitRes* result;
}

- (RoomExitRes*) defaultInstance;

- (RoomExitRes_Builder*) clear;
- (RoomExitRes_Builder*) clone;

- (RoomExitRes*) build;
- (RoomExitRes*) buildPartial;

- (RoomExitRes_Builder*) mergeFrom:(RoomExitRes*) other;
- (RoomExitRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RoomExitRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (RoomExitRes_Builder*) setUserId:(int32_t) value;
- (RoomExitRes_Builder*) clearUserId;
@end

