// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BuyShopReq;
@class BuyShopReq_Builder;
@class BuyShopRes;
@class BuyShopRes_Builder;
@class GetShopListReq;
@class GetShopListReq_Builder;
@class GetShopListRes;
@class GetShopListRes_Builder;
@class ShopInfo;
@class ShopInfo_Builder;

@interface ShopRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetShopListReq : PBGeneratedMessage {
@private
  BOOL hasShopId_:1;
  BOOL hasCount_:1;
  BOOL hasChannelId_:1;
  int32_t shopId;
  int32_t count;
  int32_t channelId;
}
- (BOOL) hasShopId;
- (BOOL) hasCount;
- (BOOL) hasChannelId;
@property (readonly) int32_t shopId;
@property (readonly) int32_t count;
@property (readonly) int32_t channelId;

+ (GetShopListReq*) defaultInstance;
- (GetShopListReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetShopListReq_Builder*) builder;
+ (GetShopListReq_Builder*) builder;
+ (GetShopListReq_Builder*) builderWithPrototype:(GetShopListReq*) prototype;

+ (GetShopListReq*) parseFromData:(NSData*) data;
+ (GetShopListReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetShopListReq*) parseFromInputStream:(NSInputStream*) input;
+ (GetShopListReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetShopListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetShopListReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetShopListReq_Builder : PBGeneratedMessage_Builder {
@private
  GetShopListReq* result;
}

- (GetShopListReq*) defaultInstance;

- (GetShopListReq_Builder*) clear;
- (GetShopListReq_Builder*) clone;

- (GetShopListReq*) build;
- (GetShopListReq*) buildPartial;

- (GetShopListReq_Builder*) mergeFrom:(GetShopListReq*) other;
- (GetShopListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetShopListReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasShopId;
- (int32_t) shopId;
- (GetShopListReq_Builder*) setShopId:(int32_t) value;
- (GetShopListReq_Builder*) clearShopId;

- (BOOL) hasCount;
- (int32_t) count;
- (GetShopListReq_Builder*) setCount:(int32_t) value;
- (GetShopListReq_Builder*) clearCount;

- (BOOL) hasChannelId;
- (int32_t) channelId;
- (GetShopListReq_Builder*) setChannelId:(int32_t) value;
- (GetShopListReq_Builder*) clearChannelId;
@end

@interface ShopInfo : PBGeneratedMessage {
@private
  BOOL hasShopId_:1;
  BOOL hasShopPrice_:1;
  BOOL hasShopName_:1;
  BOOL hasShopDesc_:1;
  BOOL hasShopPhoto_:1;
  BOOL hasProductId_:1;
  int32_t shopId;
  int32_t shopPrice;
  NSString* shopName;
  NSString* shopDesc;
  NSString* shopPhoto;
  NSString* productId;
}
- (BOOL) hasShopId;
- (BOOL) hasShopName;
- (BOOL) hasShopPrice;
- (BOOL) hasShopDesc;
- (BOOL) hasShopPhoto;
- (BOOL) hasProductId;
@property (readonly) int32_t shopId;
@property (readonly, retain) NSString* shopName;
@property (readonly) int32_t shopPrice;
@property (readonly, retain) NSString* shopDesc;
@property (readonly, retain) NSString* shopPhoto;
@property (readonly, retain) NSString* productId;

+ (ShopInfo*) defaultInstance;
- (ShopInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ShopInfo_Builder*) builder;
+ (ShopInfo_Builder*) builder;
+ (ShopInfo_Builder*) builderWithPrototype:(ShopInfo*) prototype;

+ (ShopInfo*) parseFromData:(NSData*) data;
+ (ShopInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShopInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ShopInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShopInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ShopInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ShopInfo_Builder : PBGeneratedMessage_Builder {
@private
  ShopInfo* result;
}

- (ShopInfo*) defaultInstance;

- (ShopInfo_Builder*) clear;
- (ShopInfo_Builder*) clone;

- (ShopInfo*) build;
- (ShopInfo*) buildPartial;

- (ShopInfo_Builder*) mergeFrom:(ShopInfo*) other;
- (ShopInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ShopInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasShopId;
- (int32_t) shopId;
- (ShopInfo_Builder*) setShopId:(int32_t) value;
- (ShopInfo_Builder*) clearShopId;

- (BOOL) hasShopName;
- (NSString*) shopName;
- (ShopInfo_Builder*) setShopName:(NSString*) value;
- (ShopInfo_Builder*) clearShopName;

- (BOOL) hasShopPrice;
- (int32_t) shopPrice;
- (ShopInfo_Builder*) setShopPrice:(int32_t) value;
- (ShopInfo_Builder*) clearShopPrice;

- (BOOL) hasShopDesc;
- (NSString*) shopDesc;
- (ShopInfo_Builder*) setShopDesc:(NSString*) value;
- (ShopInfo_Builder*) clearShopDesc;

- (BOOL) hasShopPhoto;
- (NSString*) shopPhoto;
- (ShopInfo_Builder*) setShopPhoto:(NSString*) value;
- (ShopInfo_Builder*) clearShopPhoto;

- (BOOL) hasProductId;
- (NSString*) productId;
- (ShopInfo_Builder*) setProductId:(NSString*) value;
- (ShopInfo_Builder*) clearProductId;
@end

@interface GetShopListRes : PBGeneratedMessage {
@private
  NSMutableArray* mutableShopInfosList;
}
- (NSArray*) shopInfosList;
- (ShopInfo*) shopInfosAtIndex:(int32_t) index;

+ (GetShopListRes*) defaultInstance;
- (GetShopListRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetShopListRes_Builder*) builder;
+ (GetShopListRes_Builder*) builder;
+ (GetShopListRes_Builder*) builderWithPrototype:(GetShopListRes*) prototype;

+ (GetShopListRes*) parseFromData:(NSData*) data;
+ (GetShopListRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetShopListRes*) parseFromInputStream:(NSInputStream*) input;
+ (GetShopListRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetShopListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetShopListRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetShopListRes_Builder : PBGeneratedMessage_Builder {
@private
  GetShopListRes* result;
}

- (GetShopListRes*) defaultInstance;

- (GetShopListRes_Builder*) clear;
- (GetShopListRes_Builder*) clone;

- (GetShopListRes*) build;
- (GetShopListRes*) buildPartial;

- (GetShopListRes_Builder*) mergeFrom:(GetShopListRes*) other;
- (GetShopListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetShopListRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) shopInfosList;
- (ShopInfo*) shopInfosAtIndex:(int32_t) index;
- (GetShopListRes_Builder*) replaceShopInfosAtIndex:(int32_t) index with:(ShopInfo*) value;
- (GetShopListRes_Builder*) addShopInfos:(ShopInfo*) value;
- (GetShopListRes_Builder*) addAllShopInfos:(NSArray*) values;
- (GetShopListRes_Builder*) clearShopInfosList;
@end

@interface BuyShopReq : PBGeneratedMessage {
@private
  BOOL hasShopId_:1;
  BOOL hasChannelId_:1;
  BOOL hasSign_:1;
  int32_t shopId;
  int32_t channelId;
  NSString* sign;
}
- (BOOL) hasShopId;
- (BOOL) hasChannelId;
- (BOOL) hasSign;
@property (readonly) int32_t shopId;
@property (readonly) int32_t channelId;
@property (readonly, retain) NSString* sign;

+ (BuyShopReq*) defaultInstance;
- (BuyShopReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BuyShopReq_Builder*) builder;
+ (BuyShopReq_Builder*) builder;
+ (BuyShopReq_Builder*) builderWithPrototype:(BuyShopReq*) prototype;

+ (BuyShopReq*) parseFromData:(NSData*) data;
+ (BuyShopReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuyShopReq*) parseFromInputStream:(NSInputStream*) input;
+ (BuyShopReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuyShopReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BuyShopReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BuyShopReq_Builder : PBGeneratedMessage_Builder {
@private
  BuyShopReq* result;
}

- (BuyShopReq*) defaultInstance;

- (BuyShopReq_Builder*) clear;
- (BuyShopReq_Builder*) clone;

- (BuyShopReq*) build;
- (BuyShopReq*) buildPartial;

- (BuyShopReq_Builder*) mergeFrom:(BuyShopReq*) other;
- (BuyShopReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BuyShopReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasShopId;
- (int32_t) shopId;
- (BuyShopReq_Builder*) setShopId:(int32_t) value;
- (BuyShopReq_Builder*) clearShopId;

- (BOOL) hasChannelId;
- (int32_t) channelId;
- (BuyShopReq_Builder*) setChannelId:(int32_t) value;
- (BuyShopReq_Builder*) clearChannelId;

- (BOOL) hasSign;
- (NSString*) sign;
- (BuyShopReq_Builder*) setSign:(NSString*) value;
- (BuyShopReq_Builder*) clearSign;
@end

@interface BuyShopRes : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasSign_:1;
  int32_t status;
  NSString* sign;
}
- (BOOL) hasStatus;
- (BOOL) hasSign;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* sign;

+ (BuyShopRes*) defaultInstance;
- (BuyShopRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BuyShopRes_Builder*) builder;
+ (BuyShopRes_Builder*) builder;
+ (BuyShopRes_Builder*) builderWithPrototype:(BuyShopRes*) prototype;

+ (BuyShopRes*) parseFromData:(NSData*) data;
+ (BuyShopRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuyShopRes*) parseFromInputStream:(NSInputStream*) input;
+ (BuyShopRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BuyShopRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BuyShopRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BuyShopRes_Builder : PBGeneratedMessage_Builder {
@private
  BuyShopRes* result;
}

- (BuyShopRes*) defaultInstance;

- (BuyShopRes_Builder*) clear;
- (BuyShopRes_Builder*) clone;

- (BuyShopRes*) build;
- (BuyShopRes*) buildPartial;

- (BuyShopRes_Builder*) mergeFrom:(BuyShopRes*) other;
- (BuyShopRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BuyShopRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (BuyShopRes_Builder*) setStatus:(int32_t) value;
- (BuyShopRes_Builder*) clearStatus;

- (BOOL) hasSign;
- (NSString*) sign;
- (BuyShopRes_Builder*) setSign:(NSString*) value;
- (BuyShopRes_Builder*) clearSign;
@end

