// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class UserAttribute;
@class UserAttributeChangeRes;
@class UserAttributeChangeRes_Builder;
@class UserAttribute_Builder;
@class UserLoginReq;
@class UserLoginReq_Builder;
@class UserLoginRes;
@class UserLoginRes_Builder;
@class UserRegisterReq;
@class UserRegisterReq_Builder;
@class UserRegisterRes;
@class UserRegisterRes_Builder;
@class UserThreeBindReq;
@class UserThreeBindReq_Builder;
@class UserThreeBindRes;
@class UserThreeBindRes_Builder;

@interface UserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UserRegisterReq : PBGeneratedMessage {
@private
  BOOL hasVersionCode_:1;
  BOOL hasRobotModel_:1;
  BOOL hasPlatformCode_:1;
  BOOL hasUuid_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  int32_t versionCode;
  int32_t robotModel;
  int32_t platformCode;
  NSString* uuid;
  NSString* userName;
  NSString* password;
}
- (BOOL) hasUuid;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasVersionCode;
- (BOOL) hasRobotModel;
- (BOOL) hasPlatformCode;
@property (readonly, retain) NSString* uuid;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly) int32_t versionCode;
@property (readonly) int32_t robotModel;
@property (readonly) int32_t platformCode;

+ (UserRegisterReq*) defaultInstance;
- (UserRegisterReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserRegisterReq_Builder*) builder;
+ (UserRegisterReq_Builder*) builder;
+ (UserRegisterReq_Builder*) builderWithPrototype:(UserRegisterReq*) prototype;

+ (UserRegisterReq*) parseFromData:(NSData*) data;
+ (UserRegisterReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserRegisterReq*) parseFromInputStream:(NSInputStream*) input;
+ (UserRegisterReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserRegisterReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserRegisterReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserRegisterReq_Builder : PBGeneratedMessage_Builder {
@private
  UserRegisterReq* result;
}

- (UserRegisterReq*) defaultInstance;

- (UserRegisterReq_Builder*) clear;
- (UserRegisterReq_Builder*) clone;

- (UserRegisterReq*) build;
- (UserRegisterReq*) buildPartial;

- (UserRegisterReq_Builder*) mergeFrom:(UserRegisterReq*) other;
- (UserRegisterReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserRegisterReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (UserRegisterReq_Builder*) setUuid:(NSString*) value;
- (UserRegisterReq_Builder*) clearUuid;

- (BOOL) hasUserName;
- (NSString*) userName;
- (UserRegisterReq_Builder*) setUserName:(NSString*) value;
- (UserRegisterReq_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (UserRegisterReq_Builder*) setPassword:(NSString*) value;
- (UserRegisterReq_Builder*) clearPassword;

- (BOOL) hasVersionCode;
- (int32_t) versionCode;
- (UserRegisterReq_Builder*) setVersionCode:(int32_t) value;
- (UserRegisterReq_Builder*) clearVersionCode;

- (BOOL) hasRobotModel;
- (int32_t) robotModel;
- (UserRegisterReq_Builder*) setRobotModel:(int32_t) value;
- (UserRegisterReq_Builder*) clearRobotModel;

- (BOOL) hasPlatformCode;
- (int32_t) platformCode;
- (UserRegisterReq_Builder*) setPlatformCode:(int32_t) value;
- (UserRegisterReq_Builder*) clearPlatformCode;
@end

@interface UserRegisterRes : PBGeneratedMessage {
@private
  BOOL hasExperience_:1;
  BOOL hasNextExperience_:1;
  BOOL hasCoin_:1;
  BOOL hasUserId_:1;
  BOOL hasRank_:1;
  BOOL hasLottery_:1;
  BOOL hasVip_:1;
  BOOL hasUserName_:1;
  BOOL hasPhotoUrl_:1;
  int64_t experience;
  int64_t nextExperience;
  int64_t coin;
  int32_t userId;
  int32_t rank;
  int32_t lottery;
  int32_t vip;
  NSString* userName;
  NSString* photoUrl;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasRank;
- (BOOL) hasExperience;
- (BOOL) hasNextExperience;
- (BOOL) hasCoin;
- (BOOL) hasLottery;
- (BOOL) hasPhotoUrl;
- (BOOL) hasVip;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly) int32_t rank;
@property (readonly) int64_t experience;
@property (readonly) int64_t nextExperience;
@property (readonly) int64_t coin;
@property (readonly) int32_t lottery;
@property (readonly, retain) NSString* photoUrl;
@property (readonly) int32_t vip;

+ (UserRegisterRes*) defaultInstance;
- (UserRegisterRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserRegisterRes_Builder*) builder;
+ (UserRegisterRes_Builder*) builder;
+ (UserRegisterRes_Builder*) builderWithPrototype:(UserRegisterRes*) prototype;

+ (UserRegisterRes*) parseFromData:(NSData*) data;
+ (UserRegisterRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserRegisterRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserRegisterRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserRegisterRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserRegisterRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserRegisterRes_Builder : PBGeneratedMessage_Builder {
@private
  UserRegisterRes* result;
}

- (UserRegisterRes*) defaultInstance;

- (UserRegisterRes_Builder*) clear;
- (UserRegisterRes_Builder*) clone;

- (UserRegisterRes*) build;
- (UserRegisterRes*) buildPartial;

- (UserRegisterRes_Builder*) mergeFrom:(UserRegisterRes*) other;
- (UserRegisterRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserRegisterRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserRegisterRes_Builder*) setUserId:(int32_t) value;
- (UserRegisterRes_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (UserRegisterRes_Builder*) setUserName:(NSString*) value;
- (UserRegisterRes_Builder*) clearUserName;

- (BOOL) hasRank;
- (int32_t) rank;
- (UserRegisterRes_Builder*) setRank:(int32_t) value;
- (UserRegisterRes_Builder*) clearRank;

- (BOOL) hasExperience;
- (int64_t) experience;
- (UserRegisterRes_Builder*) setExperience:(int64_t) value;
- (UserRegisterRes_Builder*) clearExperience;

- (BOOL) hasNextExperience;
- (int64_t) nextExperience;
- (UserRegisterRes_Builder*) setNextExperience:(int64_t) value;
- (UserRegisterRes_Builder*) clearNextExperience;

- (BOOL) hasCoin;
- (int64_t) coin;
- (UserRegisterRes_Builder*) setCoin:(int64_t) value;
- (UserRegisterRes_Builder*) clearCoin;

- (BOOL) hasLottery;
- (int32_t) lottery;
- (UserRegisterRes_Builder*) setLottery:(int32_t) value;
- (UserRegisterRes_Builder*) clearLottery;

- (BOOL) hasPhotoUrl;
- (NSString*) photoUrl;
- (UserRegisterRes_Builder*) setPhotoUrl:(NSString*) value;
- (UserRegisterRes_Builder*) clearPhotoUrl;

- (BOOL) hasVip;
- (int32_t) vip;
- (UserRegisterRes_Builder*) setVip:(int32_t) value;
- (UserRegisterRes_Builder*) clearVip;
@end

@interface UserThreeBindReq : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasShareType_:1;
  BOOL hasShareId_:1;
  BOOL hasAccessToken_:1;
  BOOL hasRefreshToken_:1;
  int32_t userId;
  int32_t shareType;
  NSString* shareId;
  NSString* accessToken;
  NSString* refreshToken;
}
- (BOOL) hasUserId;
- (BOOL) hasShareId;
- (BOOL) hasShareType;
- (BOOL) hasAccessToken;
- (BOOL) hasRefreshToken;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* shareId;
@property (readonly) int32_t shareType;
@property (readonly, retain) NSString* accessToken;
@property (readonly, retain) NSString* refreshToken;

+ (UserThreeBindReq*) defaultInstance;
- (UserThreeBindReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserThreeBindReq_Builder*) builder;
+ (UserThreeBindReq_Builder*) builder;
+ (UserThreeBindReq_Builder*) builderWithPrototype:(UserThreeBindReq*) prototype;

+ (UserThreeBindReq*) parseFromData:(NSData*) data;
+ (UserThreeBindReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserThreeBindReq*) parseFromInputStream:(NSInputStream*) input;
+ (UserThreeBindReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserThreeBindReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserThreeBindReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserThreeBindReq_Builder : PBGeneratedMessage_Builder {
@private
  UserThreeBindReq* result;
}

- (UserThreeBindReq*) defaultInstance;

- (UserThreeBindReq_Builder*) clear;
- (UserThreeBindReq_Builder*) clone;

- (UserThreeBindReq*) build;
- (UserThreeBindReq*) buildPartial;

- (UserThreeBindReq_Builder*) mergeFrom:(UserThreeBindReq*) other;
- (UserThreeBindReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserThreeBindReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserThreeBindReq_Builder*) setUserId:(int32_t) value;
- (UserThreeBindReq_Builder*) clearUserId;

- (BOOL) hasShareId;
- (NSString*) shareId;
- (UserThreeBindReq_Builder*) setShareId:(NSString*) value;
- (UserThreeBindReq_Builder*) clearShareId;

- (BOOL) hasShareType;
- (int32_t) shareType;
- (UserThreeBindReq_Builder*) setShareType:(int32_t) value;
- (UserThreeBindReq_Builder*) clearShareType;

- (BOOL) hasAccessToken;
- (NSString*) accessToken;
- (UserThreeBindReq_Builder*) setAccessToken:(NSString*) value;
- (UserThreeBindReq_Builder*) clearAccessToken;

- (BOOL) hasRefreshToken;
- (NSString*) refreshToken;
- (UserThreeBindReq_Builder*) setRefreshToken:(NSString*) value;
- (UserThreeBindReq_Builder*) clearRefreshToken;
@end

@interface UserThreeBindRes : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasReason_:1;
  int32_t status;
  NSString* reason;
}
- (BOOL) hasStatus;
- (BOOL) hasReason;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* reason;

+ (UserThreeBindRes*) defaultInstance;
- (UserThreeBindRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserThreeBindRes_Builder*) builder;
+ (UserThreeBindRes_Builder*) builder;
+ (UserThreeBindRes_Builder*) builderWithPrototype:(UserThreeBindRes*) prototype;

+ (UserThreeBindRes*) parseFromData:(NSData*) data;
+ (UserThreeBindRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserThreeBindRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserThreeBindRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserThreeBindRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserThreeBindRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserThreeBindRes_Builder : PBGeneratedMessage_Builder {
@private
  UserThreeBindRes* result;
}

- (UserThreeBindRes*) defaultInstance;

- (UserThreeBindRes_Builder*) clear;
- (UserThreeBindRes_Builder*) clone;

- (UserThreeBindRes*) build;
- (UserThreeBindRes*) buildPartial;

- (UserThreeBindRes_Builder*) mergeFrom:(UserThreeBindRes*) other;
- (UserThreeBindRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserThreeBindRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (UserThreeBindRes_Builder*) setStatus:(int32_t) value;
- (UserThreeBindRes_Builder*) clearStatus;

- (BOOL) hasReason;
- (NSString*) reason;
- (UserThreeBindRes_Builder*) setReason:(NSString*) value;
- (UserThreeBindRes_Builder*) clearReason;
@end

@interface UserLoginReq : PBGeneratedMessage {
@private
  BOOL hasVersionCode_:1;
  BOOL hasPlatformCode_:1;
  BOOL hasUuid_:1;
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  int32_t versionCode;
  int32_t platformCode;
  NSString* uuid;
  NSString* userName;
  NSString* password;
}
- (BOOL) hasUuid;
- (BOOL) hasUserName;
- (BOOL) hasPassword;
- (BOOL) hasVersionCode;
- (BOOL) hasPlatformCode;
@property (readonly, retain) NSString* uuid;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;
@property (readonly) int32_t versionCode;
@property (readonly) int32_t platformCode;

+ (UserLoginReq*) defaultInstance;
- (UserLoginReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserLoginReq_Builder*) builder;
+ (UserLoginReq_Builder*) builder;
+ (UserLoginReq_Builder*) builderWithPrototype:(UserLoginReq*) prototype;

+ (UserLoginReq*) parseFromData:(NSData*) data;
+ (UserLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (UserLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserLoginReq_Builder : PBGeneratedMessage_Builder {
@private
  UserLoginReq* result;
}

- (UserLoginReq*) defaultInstance;

- (UserLoginReq_Builder*) clear;
- (UserLoginReq_Builder*) clone;

- (UserLoginReq*) build;
- (UserLoginReq*) buildPartial;

- (UserLoginReq_Builder*) mergeFrom:(UserLoginReq*) other;
- (UserLoginReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserLoginReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (UserLoginReq_Builder*) setUuid:(NSString*) value;
- (UserLoginReq_Builder*) clearUuid;

- (BOOL) hasUserName;
- (NSString*) userName;
- (UserLoginReq_Builder*) setUserName:(NSString*) value;
- (UserLoginReq_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (UserLoginReq_Builder*) setPassword:(NSString*) value;
- (UserLoginReq_Builder*) clearPassword;

- (BOOL) hasVersionCode;
- (int32_t) versionCode;
- (UserLoginReq_Builder*) setVersionCode:(int32_t) value;
- (UserLoginReq_Builder*) clearVersionCode;

- (BOOL) hasPlatformCode;
- (int32_t) platformCode;
- (UserLoginReq_Builder*) setPlatformCode:(int32_t) value;
- (UserLoginReq_Builder*) clearPlatformCode;
@end

@interface UserLoginRes : PBGeneratedMessage {
@private
  BOOL hasExperience_:1;
  BOOL hasNextExperience_:1;
  BOOL hasUserId_:1;
  BOOL hasRank_:1;
  BOOL hasCoin_:1;
  BOOL hasLottery_:1;
  BOOL hasVip_:1;
  BOOL hasUserName_:1;
  BOOL hasPhotoUrl_:1;
  int64_t experience;
  int64_t nextExperience;
  int32_t userId;
  int32_t rank;
  int32_t coin;
  int32_t lottery;
  int32_t vip;
  NSString* userName;
  NSString* photoUrl;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasRank;
- (BOOL) hasExperience;
- (BOOL) hasNextExperience;
- (BOOL) hasCoin;
- (BOOL) hasLottery;
- (BOOL) hasPhotoUrl;
- (BOOL) hasVip;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly) int32_t rank;
@property (readonly) int64_t experience;
@property (readonly) int64_t nextExperience;
@property (readonly) int32_t coin;
@property (readonly) int32_t lottery;
@property (readonly, retain) NSString* photoUrl;
@property (readonly) int32_t vip;

+ (UserLoginRes*) defaultInstance;
- (UserLoginRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserLoginRes_Builder*) builder;
+ (UserLoginRes_Builder*) builder;
+ (UserLoginRes_Builder*) builderWithPrototype:(UserLoginRes*) prototype;

+ (UserLoginRes*) parseFromData:(NSData*) data;
+ (UserLoginRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLoginRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserLoginRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserLoginRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserLoginRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserLoginRes_Builder : PBGeneratedMessage_Builder {
@private
  UserLoginRes* result;
}

- (UserLoginRes*) defaultInstance;

- (UserLoginRes_Builder*) clear;
- (UserLoginRes_Builder*) clone;

- (UserLoginRes*) build;
- (UserLoginRes*) buildPartial;

- (UserLoginRes_Builder*) mergeFrom:(UserLoginRes*) other;
- (UserLoginRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserLoginRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserLoginRes_Builder*) setUserId:(int32_t) value;
- (UserLoginRes_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (UserLoginRes_Builder*) setUserName:(NSString*) value;
- (UserLoginRes_Builder*) clearUserName;

- (BOOL) hasRank;
- (int32_t) rank;
- (UserLoginRes_Builder*) setRank:(int32_t) value;
- (UserLoginRes_Builder*) clearRank;

- (BOOL) hasExperience;
- (int64_t) experience;
- (UserLoginRes_Builder*) setExperience:(int64_t) value;
- (UserLoginRes_Builder*) clearExperience;

- (BOOL) hasNextExperience;
- (int64_t) nextExperience;
- (UserLoginRes_Builder*) setNextExperience:(int64_t) value;
- (UserLoginRes_Builder*) clearNextExperience;

- (BOOL) hasCoin;
- (int32_t) coin;
- (UserLoginRes_Builder*) setCoin:(int32_t) value;
- (UserLoginRes_Builder*) clearCoin;

- (BOOL) hasLottery;
- (int32_t) lottery;
- (UserLoginRes_Builder*) setLottery:(int32_t) value;
- (UserLoginRes_Builder*) clearLottery;

- (BOOL) hasPhotoUrl;
- (NSString*) photoUrl;
- (UserLoginRes_Builder*) setPhotoUrl:(NSString*) value;
- (UserLoginRes_Builder*) clearPhotoUrl;

- (BOOL) hasVip;
- (int32_t) vip;
- (UserLoginRes_Builder*) setVip:(int32_t) value;
- (UserLoginRes_Builder*) clearVip;
@end

@interface UserAttribute : PBGeneratedMessage {
@private
  BOOL hasAttribute_:1;
  BOOL hasValue_:1;
  NSString* attribute;
  NSString* value;
}
- (BOOL) hasAttribute;
- (BOOL) hasValue;
@property (readonly, retain) NSString* attribute;
@property (readonly, retain) NSString* value;

+ (UserAttribute*) defaultInstance;
- (UserAttribute*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserAttribute_Builder*) builder;
+ (UserAttribute_Builder*) builder;
+ (UserAttribute_Builder*) builderWithPrototype:(UserAttribute*) prototype;

+ (UserAttribute*) parseFromData:(NSData*) data;
+ (UserAttribute*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttribute*) parseFromInputStream:(NSInputStream*) input;
+ (UserAttribute*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttribute*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserAttribute*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserAttribute_Builder : PBGeneratedMessage_Builder {
@private
  UserAttribute* result;
}

- (UserAttribute*) defaultInstance;

- (UserAttribute_Builder*) clear;
- (UserAttribute_Builder*) clone;

- (UserAttribute*) build;
- (UserAttribute*) buildPartial;

- (UserAttribute_Builder*) mergeFrom:(UserAttribute*) other;
- (UserAttribute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserAttribute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAttribute;
- (NSString*) attribute;
- (UserAttribute_Builder*) setAttribute:(NSString*) value;
- (UserAttribute_Builder*) clearAttribute;

- (BOOL) hasValue;
- (NSString*) value;
- (UserAttribute_Builder*) setValue:(NSString*) value;
- (UserAttribute_Builder*) clearValue;
@end

@interface UserAttributeChangeRes : PBGeneratedMessage {
@private
  NSMutableArray* mutableAttributeList;
}
- (NSArray*) attributeList;
- (UserAttribute*) attributeAtIndex:(int32_t) index;

+ (UserAttributeChangeRes*) defaultInstance;
- (UserAttributeChangeRes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserAttributeChangeRes_Builder*) builder;
+ (UserAttributeChangeRes_Builder*) builder;
+ (UserAttributeChangeRes_Builder*) builderWithPrototype:(UserAttributeChangeRes*) prototype;

+ (UserAttributeChangeRes*) parseFromData:(NSData*) data;
+ (UserAttributeChangeRes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttributeChangeRes*) parseFromInputStream:(NSInputStream*) input;
+ (UserAttributeChangeRes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAttributeChangeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserAttributeChangeRes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserAttributeChangeRes_Builder : PBGeneratedMessage_Builder {
@private
  UserAttributeChangeRes* result;
}

- (UserAttributeChangeRes*) defaultInstance;

- (UserAttributeChangeRes_Builder*) clear;
- (UserAttributeChangeRes_Builder*) clone;

- (UserAttributeChangeRes*) build;
- (UserAttributeChangeRes*) buildPartial;

- (UserAttributeChangeRes_Builder*) mergeFrom:(UserAttributeChangeRes*) other;
- (UserAttributeChangeRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserAttributeChangeRes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) attributeList;
- (UserAttribute*) attributeAtIndex:(int32_t) index;
- (UserAttributeChangeRes_Builder*) replaceAttributeAtIndex:(int32_t) index with:(UserAttribute*) value;
- (UserAttributeChangeRes_Builder*) addAttribute:(UserAttribute*) value;
- (UserAttributeChangeRes_Builder*) addAllAttribute:(NSArray*) values;
- (UserAttributeChangeRes_Builder*) clearAttributeList;
@end

